use coding_tools_personal_runtime::{Store,digest,locks,config};
use serde_json::json;
use std::{fs,sync::Arc,time::Duration};
fn store()->(tempfile::TempDir,tempfile::TempDir,Store){let w=tempfile::tempdir().unwrap();let d=tempfile::tempdir().unwrap();let s=Store::open(d.path(),w.path()).unwrap();(w,d,s)}
#[test] fn same_conversation_same_goal_resumes(){let(_w,_d,s)=store();let a=s.task_open("goal",Some("a"),false).unwrap();let b=s.task_open("goal",Some("a"),false).unwrap();assert_eq!(a["task_id"],b["task_id"]);assert_eq!(s.task_open("other",Some("a"),false).unwrap_err().code(),"GOAL_CONFLICT");}
#[test] fn different_conversations_do_not_steal_task(){let(_w,_d,s)=store();let a=s.task_open("one",Some("a"),false).unwrap();let b=s.task_open("two",Some("b"),false).unwrap();assert_ne!(a["task_id"],b["task_id"]);assert_eq!(s.bound_task("a").unwrap().unwrap(),a["task_id"].as_str().unwrap());}
#[test] fn restart_recovers_checkpoint_and_original_id(){let(w,d,s)=store();let t=s.task_open("long",Some("x"),false).unwrap();let id=t["task_id"].as_str().unwrap();s.task_checkpoint(&json!({"task_id":id,"request_id":"step-200","expected_revision":0,"checkpoint":{"next_step":"201","steps":{"200":{"state":"passed","evidence":["result.json"]}}}})).unwrap();drop(s);let s=Store::open(d.path(),w.path()).unwrap();assert_eq!(s.task_status(id).unwrap()["checkpoint"]["next_step"],"201");}
#[test] fn stale_checkpoint_never_overwrites_concurrent_delta(){let(_w,_d,s)=store();let t=s.task_open("g",None,false).unwrap();let mut q=json!({"task_id":t["task_id"],"request_id":"a","expected_revision":0,"checkpoint":{"next_step":"two"}});s.task_checkpoint(&q).unwrap();q["request_id"]=json!("b");assert_eq!(s.task_checkpoint(&q).unwrap_err().code(),"STALE_CHECKPOINT");}
#[test] fn repeated_checkpoint_is_idempotent(){let(_w,_d,s)=store();let t=s.task_open("g",None,false).unwrap();let q=json!({"task_id":t["task_id"],"request_id":"a","expected_revision":0,"checkpoint":{"next_step":"two"}});let a=s.task_checkpoint(&q).unwrap();assert_eq!(a,s.task_checkpoint(&q).unwrap());}
#[test] fn checkpoint_key_cannot_change_meaning(){let(_w,_d,s)=store();let t=s.task_open("g",None,false).unwrap();let mut q=json!({"task_id":t["task_id"],"request_id":"a","expected_revision":0,"checkpoint":{"next_step":"two"}});s.task_checkpoint(&q).unwrap();q["checkpoint"]["next_step"]=json!("three");assert_eq!(s.task_checkpoint(&q).unwrap_err().code(),"IDEMPOTENCY_CONFLICT");}
#[test] fn completion_requires_evidence(){let(_w,_d,s)=store();let t=s.task_open("g",None,false).unwrap();assert_eq!(s.task_checkpoint(&json!({"task_id":t["task_id"],"request_id":"a","expected_revision":0,"state":"completed","checkpoint":{}})).unwrap_err().code(),"ACCEPTANCE_MISSING");}
#[test] fn event_paging_stops_at_end(){let(_w,_d,s)=store();let t=s.task_open("g",None,false).unwrap();let id=t["task_id"].as_str().unwrap();for n in 0..3{s.event(id,"read",&json!({"n":n})).unwrap();}let first=s.events(id,0,2).unwrap();assert!(first["next_cursor"].is_i64());let last=s.events(id,first["next_cursor"].as_i64().unwrap(),2).unwrap();assert!(last["next_cursor"].is_null());assert_eq!(last["events"].as_array().unwrap().len(),1);}
#[test] fn lock_exclusive_and_shared_contract(){let(_w,_d,s)=store();let a=locks::gate(&s.dir,"source",false,Duration::ZERO).unwrap();let b=locks::gate(&s.dir,"source",false,Duration::ZERO).unwrap();assert!(locks::try_gate(&s.dir,"source",true).unwrap().is_none());drop((a,b));assert!(locks::try_gate(&s.dir,"source",true).unwrap().is_some());}
#[test] fn concurrent_tasks_persist_without_lost_updates(){let(_w,_d,s)=store();let s=Arc::new(s);let threads:Vec<_>=(0..8).map(|n|{let s=s.clone();std::thread::spawn(move||s.task_open(&format!("goal-{n}"),Some(&format!("owner-{n}")),false).unwrap())}).collect();for h in threads{h.join().unwrap();}assert_eq!(s.task_list(None,100).unwrap()["tasks"].as_array().unwrap().len(),8);}
#[test] fn uncertain_patch_receipt_cannot_replay(){let(_w,_d,s)=store();assert!(s.begin_receipt("patch","one","hash").unwrap().is_none());assert_eq!(s.begin_receipt("patch","one","hash").unwrap_err().code(),"OPERATION_INDETERMINATE");s.finish_receipt("patch","one",&json!({"saved":true})).unwrap();assert!(s.begin_receipt("patch","one","hash").unwrap().is_some());}
#[test] fn safe_config_copy_preserves_secrets_without_starting(){let d=tempfile::tempdir().unwrap();let source=d.path().join("old.json");let dest=d.path().join("personal/data/profiles.json");let data=json!({"shared_secrets":{"password":"test-only"},"profiles":[{"id":"one","path":"project","auto_start":true,"runtime":{"local_port":38766,"upstream_mcps":[{"enabled":true,"command":"not-run"}]},"tunnel":{"type":"frp","public_url":"https://old"},"actions":{"local_port":3001,"tunnel_type":"frp"}}]});fs::write(&source,data.to_string()).unwrap();let before=digest(fs::read(&source).unwrap());let receipt=config::inherit(&source,&dest).unwrap();assert_eq!(before,digest(fs::read(&source).unwrap()));let out:serde_json::Value=serde_json::from_slice(&fs::read(&dest).unwrap()).unwrap();assert_eq!(out["shared_secrets"],data["shared_secrets"]);assert_eq!(out["profiles"][0]["auto_start"],false);assert_eq!(out["profiles"][0]["tunnel"]["type"],"none");assert_eq!(out["profiles"][0]["runtime"]["upstream_mcps"][0]["enabled"],false);assert_eq!(receipt["services_started"],false);assert_ne!(out["profiles"][0]["runtime"]["local_port"],38766);assert_eq!(config::inherit(&source,&dest).unwrap_err().code(),"CONFIG_EXISTS");}
#[test] fn invalid_config_does_not_create_destination(){let d=tempfile::tempdir().unwrap();let a=d.path().join("a");let b=d.path().join("b");fs::write(&a,"not json").unwrap();assert!(config::inherit(&a,&b).is_err());assert!(!b.exists());}
#[test] fn task_id_cannot_traverse_directories(){let(_w,_d,s)=store();assert_eq!(s.task_status("../../x").unwrap_err().code(),"INVALID_ID");}
